platform :ios, '8.0'
use_frameworks!

target 'StateChamps!' do

pod 'YouTubePlayer'
pod 'Parse'
pod 'Fabric'
pod 'TwitterKit',  '1.14.6'
pod 'TwitterCore', '1.14.6'
pod 'Crashlytics'

end

target 'StateChamps!Tests' do

end

target 'StateChamps!UITests' do

end

